### ISSUE TITLE
Pagination not marked as nav

### ISSUE THREAD

**Issue by frrrances** [MITLibraries/bento#100]
Wrap the pager buttons in a nav element or container with role="navigation" and label via aria-label="pager" or equivalent

**Comment by frrrances** [comment]
Fixed upstream on kaminari: 
https://github.com/kaminari/kaminari/pull/848

https://github.com/frrrances/kaminari/tree/add-a11y-roles

**Comment by frrrances** [comment]
Merged! @JPrevost  I'll leave this open until the gem is updated and we can change our source (we're still pointing to my forked copy.)

**Comment by JPrevost** [comment]
This was resolved upstream and our Gemfile is using the official version so we're 👍
