### ISSUE TITLE
Do something about lots of authors

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/bento#22]
Some items have lots and lots of authors. It's unlikely displaying them all is useful and it sure looks bad.

**Comment by matt-bernhardt** [comment]
Do you want to limit authors to a set number? Two or three? And, is there a sample search we could use to check?

**Comment by JPrevost** [comment]
Let's use an ENV to set the number of authors so we don't have to get a final decision from stakeholders until they can see it in action. Let's say if the number of authors is more than `ENV['MAX_AUTHORS']` we just use the first author then append `et al`.

Feel free to shop that plan around more or just dig in and see how it comes out.

**Comment by matt-bernhardt** [comment]
:+1: I'll take a stab at this.
