### ISSUE TITLE
Resource "type" should be listed *after* the item's title

### ISSUE THREAD

**Issue by RichCaloggero** [MITLibraries/bento#97]
## Resource "type" should be listed *after* the item's title

Currently, an result item looks like this:

>Type: Audio
Title: BLUE MOVIES
Authors: Barbieri, Gato, Composer ; Barry, John, Composer ; Bart, Lionel, Composer ; et al 
Subjects: 
Contemporary Jazz
Source DB: Naxos Music Library Jazz (edsnmj) 
Get it

The title is marked up as a heading, but the type comes *before* the heading. If a screen reader user scans by heading, the type is skipped.

**Comment by frrrances** [comment]
Resolved with #102
