### ISSUE TITLE
Missing heading on "all results" page

### ISSUE THREAD

**Issue by RichCaloggero** [MITLibraries/bento#98]
## Missing heading on "all results" page

If you search for something, then click one of the "see all NNN results" buttons, you get to a page which lists all the results in that category as a paged result set.

- wrap the pager buttons in a `nav` element or container with `role="navigation"` and label via `aria-label="pager"` or equivalent
- the first heading after the `h1` is an `h3` wrapping the first result title; include the `h2` for catagory before the first result title

**Comment by frrrances** [comment]
Resolved with #102
